import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Navbar from "../components/navbar";
import "../styles/globals.css";
import LoadingBar from "react-top-loading-bar";
import Footer from "../components/footer";



function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const [progress, setProgress] = useState(0);

   
  useEffect(() => {
    router.events.on("routeChangeStart", () => {
      setProgress(50);
    });
    router.events.on("routeChangeComplete", () => {
      setProgress(100);
    });
    
  }, [router]);
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plant1.avif"  />
      </Head>
      <LoadingBar
        color="#4ade80"
        progress={progress}
        waitingTime={400}
        onLoaderFinished={() => setProgress(0)}
      />
      <Navbar />
      <Component {...pageProps} />
      <Footer/>
    </>
  );
}

export default MyApp;
