import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

const About = () => {
  return (
    <div className="">
      <Head>
        <title>Strong Roots About </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <style>
        {`
    .bgimg1 {
      background-image: url("/child6.jpg");
    }
  `}
      </style>
      <div className="bgimg1 h-52  bg-center bg-no-repeat bg-cover flex flex-col justify-center items-center">
        <div>
          <picture>
            <img src="/plant1.avif" alt="" className="w-28 rounded-full " />
          </picture>
        </div>
        <span
          className="text-white md:text-7xl text-xl font-semibold font-serif "
          data-aos="zoom-in-down"
          data-aos-duration="2000"
        >
          Want to know About Us ?
        </span>
      </div>
      <div className="my-6">
        <div className="text-center py-8 text-4xl text-green-600 font-serif font-bold">
          Leafy Legacy, Trees For Tomorrow
        </div>
        <div className="py-12   bg-gray-800/40 text-white md:px-24 px-3 md:text-md text-xs mx-auto indent-16 flex flex-col space-y-6  md:text-base shadow-md shadow-green-600 md:leading-7 leading-2 w-10/12">
          <div className="text-white   ">
            Welcome to Leafy Legacy, a tree planting initiative aimed at
            promoting environmental sustainability while providing a unique way
            for people to commemorate special occasions. Our mission is to plant
            native trees in public places such as schools, colleges, hospitals,
            and street sides, and care for them until they are self-sustaining
            with donor funds. We believe that every tree planted makes a
            difference. Trees are not only beautiful and essential to the
            environment, but also provide numerous benefits to the community,
            such as reducing air pollution, creating shade and shelter, and
            improving overall well-being. By planting trees in public places, we
            hope to create a greener and more livable community for everyone to
            enjoy. <br />
          </div>
          <div>
            At Leafy Legacy, we offer a special way for people to celebrate
            their special occasions, such as birthdays, anniversaries, and
            remembrance days, by donating trees and funds in their name. Not
            only does this provide a unique and meaningful way to celebrate, but
            it also helps create a lasting legacy by contributing to a healthier
            environment for future generations.
          </div>
          <div>
            We carefully select and plant only native trees that are well-suited
            to the local climate and environment, and ensure that each tree
            receives the proper care and attention it needs to thrive with help
            of funds donated. Our team works closely with schools, colleges,
            hospitals, and other public places to identify ideal planting
            locations and ensure that the trees are well-maintained over time. 2
            Join us in our mission to make our community greener, healthier, and
            more sustainable, one tree at a time. Contact us to learn more about
            how you can donate and make a lasting impact on the environment and
            the community. Thank you for your support!
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center space-y-2 pt-6 justify-center text-white" >
        <p className={styles.meet}  >Meet Our</p>
        <p className="text-3xl uppercase  font-semibold tracking-wider " >Team</p>
      </div>
      <section className="text-gray-400  body-font">
        <div className="container px-5 pb-12 pt-36 mx-auto">
          <div className="flex flex-wrap -m-4">
            <div className="p-4 lg:w-1/3 relative ">
            <picture className="absolute md:-top-16 -top-8 md:left-40 left-28 z-30 mx-auto  md:w-48 w-36 ">
                <img src="/pranay1.jpg" alt="" className="object-cover object-center rounded-full " />
              </picture>
              <div className="h-full bg-gray-800 bg-opacity-40 px-8 pt-36 pb-12 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                  OPERATIONS COORDINATOR
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-white mb-3">
                  B - Santosh Kumar
                </h1>
                <p className="leading-relaxed mb-3">BSC Statistics</p>
                <p className="text-green-400 inline-flex items-center">
                  Gayatri Vidya parisadh UG and PG college
                </p>
                
              </div>
            </div>
            <div className="p-4 lg:w-1/3 relative">
              <picture className="absolute md:-top-16 md:left-40 z-30 mx-auto  md:w-48 left-28 -top-8 w-36 ">
                <img src="/pranay.jpg" alt="" className="object-cover object-center rounded-full " />
              </picture>
              <div className="h-full bg-gray-800 bg-opacity-40 px-8 pt-36 pb-12 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                  PROGRAM MANAGER
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-white mb-3">
                  K - Pranay Venkat Sai
                </h1>
                <p className="leading-relaxed mb-3">BSC Statistics</p>
                <p className="text-green-400 inline-flex items-center">
                  Gayatri Vidya parisadh UG and PG college
                </p>
               
              </div>
            </div>
            <div className="p-4 lg:w-1/3 relative ">
            <picture className="absolute md:-top-16 md:left-40 z-30 mx-auto  md:w-48 w-36 -top-8 left-28 ">
                <img src="/pranay2.jpg" alt="" className="object-cover object-center rounded-full " />
              </picture>
              <div className="h-full bg-gray-800 bg-opacity-40 px-8 pt-36 pb-12 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                  PROJECT MANAGER
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-white mb-3">
                  R - Durga Prasad
                </h1>
                <p className="leading-relaxed mb-3">BSC Physics</p>
                <p className="text-green-400 inline-flex items-center">
                  Gayatri Vidya parisadh UG and PG college
                </p>
               
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default About;
