import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { RiPlantLine } from "react-icons/ri";
import styles from "../styles/Home.module.css";
import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/splide/dist/css/themes/splide-skyblue.min.css";
import AOS from "aos";

import "aos/dist/aos.css";
import { useEffect, useRef } from "react";
import About from "./about";
import Plant from "./plant";
import Navbar from "../components/navbar";

export default function Home() {
  useEffect(() => {
    AOS.init();
  });
  const gain = useRef();
  const func = () => {
    gain.current.style.width = "200px";
    gain.current.style.top = "100px";
    console.log(gain);
  };
  return (
    <div className="">
      <Head>
        <title>Strong Roots Foundation</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <style jsx >
        {`
         
          .scroll1 {
            background-image: url("/plant10.jpg");
          }
          .scroll2 {
            background-image: url("/plant16.jpg");
          }
          .scroll3 {
            background-image: url("/child3.jpg");
          }
          .scroll4 {
            background-image: url("/child4.jpeg");
          }
          .scroll5 {
            background-image: url("/child2.avif");
          }
          .scroll6 {
            background-image: url("/child1.jpg");
          }
        `}
      </style>
      <Splide>
        <SplideSlide>
          <div className="scroll6 md:h-[560px] h-52 bg-clip-padding   md:bg-fill bg-cover   bg-no-repeat bg-center flex justify-center items-center">
            <div className="-mt-4">
              <picture>
                <img
                  src="/plant1.avif"
                  alt=""
                  className="w-28 animate-pulse rounded-full mx-auto "
                />
              </picture>
              <p
                className={`${styles.welcome} md:block hidden `}
                data-aos="zoom-in-down"
                data-aos-duration="2000"
              >
                Welcome To
              </p>
              <span
                className="mx-3 md:text-[80px]   text-white font-bold  text-xl   font-serif "
                data-aos="fade-up"
                data-aos-duration="2000"
              >
                Strong Roots Foundation
              </span>
            </div>
          </div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll1 md:h-[560px] h-52 bg-clip-padding bg-cover  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll5 md:h-[560px] h-52 bg-clip-padding  bg-cover md:scale-x-100 md:scale-y-100 scale-y-125  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll2 md:h-[560px] h-52 bg-clip-padding   bg-cover  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll3 md:h-[560px] h-52 bg-clip-padding  md:bg-cover bg-contain md:scale-y-100 scale-y-175  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll4 md:h-[560px] h-52 bg-clip-padding  bg-cover  bg-no-repeat bg-center"></div>
        </SplideSlide>
      </Splide>

      <section className="text-gray-400  body-font">
        <div className="container px-5 py-8 mx-auto">
          <div className="flex  flex-col  justify-center items-center space-y-2">
            <span className={styles.support}>Support</span>
            <span className="pb-12 text-white text-4xl font-thin font-serif underline underline-offset-4  ">
              Curent Projects
            </span>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="p-4 md:w-1/3">
              <div className="h-full border-2 border-gray-800 shadow-md shadow-green-500 rounded-lg overflow-hidden">
                <picture>
                  <img
                    className="lg:h-56 md:h-36 w-full object-cover object-center"
                    src="/school1.jpg"
                    alt="blog"
                  />
                </picture>
                <div className="p-6">
                  <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                    Name of the Institute
                  </h2>
                  <h1 className="title-font text-lg font-medium text-white mb-3">
                    Jawahar Navodaya Vidyalaya
                  </h1>
                  <p className="leading-relaxed mb-3">
                    Tree plantation with students of jawahar navodaya vidyalay
                    and nearby regions in Kommadi.
                  </p>
                  <div className="flex items-center flex-wrap ">
                    <span className="text-green-400 inline-flex items-center md:mb-2 lg:mb-0">
                      <span className="tracking-widest text-xs title-font font-medium text-gray-500">
                        people Involved :{" "}
                      </span>{" "}
                      &nbsp;700
                    </span>
                    <RiPlantLine className="ml-auto text-xl text-blue-500 font-bold" />

                  </div>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3">
              <div className="h-full  shadow-md shadow-green-500  rounded-lg overflow-hidden">
                <picture>
                  <img
                    className="lg:h-56 md:h-36 w-full object-cover object-center"
                    src="/school2.jpeg"
                    alt="blog"
                  />
                </picture>
                <div className="p-6">
                  <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                    Name of the Institute
                  </h2>
                  <h1 className="title-font text-lg font-medium text-white mb-3">
                    GVMC Hospital and Dispencary
                  </h1>
                  <p className="leading-relaxed mb-3">
                    Tree plantation with people of institute and nearby regions
                    in vizag.
                  </p>
                  <div className="flex items-center flex-wrap">
                    <span className="text-green-400 inline-flex items-center md:mb-2 lg:mb-0">
                      <span className="tracking-widest text-xs title-font font-medium text-gray-500">
                        people Involved :{" "}
                      </span>{" "}
                      &nbsp;1200
                    </span>
                    
                      <RiPlantLine className="ml-auto text-xl text-blue-500 font-bold" />
                   
                  </div>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3">
              <div className="h-full  shadow-md shadow-green-500  rounded-lg overflow-hidden">
                <picture>
                  <img
                    className="lg:h-56 md:h-36 w-full object-cover object-center"
                    src="/school4.png"
                    alt="blog"
                  />
                </picture>
                <div className="p-6">
                  <h2 className="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">
                    Name of the Institute
                  </h2>
                  <h1 className="title-font text-lg font-medium text-white mb-3">
                    Govt High School , Pendurthi
                  </h1>
                  <p className="leading-relaxed mb-3">
                    Tree plantation with people of institute and nearby regions
                    in pendurthi.
                  </p>
                  <div className="flex items-center flex-wrap ">
                    <span className="text-green-400 inline-flex items-center md:mb-2 lg:mb-0">
                      <span className="tracking-widest text-xs title-font font-medium text-gray-500">
                        people Involved :{" "}
                      </span>{" "}
                      &nbsp;300
                    </span>
                    <RiPlantLine className="ml-auto text-xl text-blue-500 font-bold" />
                   
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="mx-auto text-center py-2 px-4 hover:scale-110 transition ease-in-out text-white hover:bg-green-600 rounded-lg my-8  bg-gray-800 duration-500 w-fit ">
            <Link href={"./plant"}>
              <a> View More Projects </a>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
