import React, { useEffect } from "react";

import { Canvas } from "@react-three/fiber";
import Experience from "../components/experience";

import styles from "../styles/Home.module.css";
import Head from "next/head";

const Model = () => {
  return (
    <>
    <Head>
        <title>Strong Roots model</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={`${styles.maya}`}>
        <Canvas
          shadows
          camera={{
            fov: 45,
            near: 0.1,
            far: 200,
            position: [-4, 3, 6],
          }}
        >
          <Experience />
        </Canvas>
      </div>
    </>
  );
};

export default Model;
