import React, { useEffect, useState } from "react";
import { files } from "../data/files";
import { mandal } from "../data/mandal";
import AOS from "aos";

import "aos/dist/aos.css";
import Head from "next/head";
console.log(files);

const Plant = ({ school, village }) => {
 
  useEffect(()=>{
    village.sort();
  })

  const [name, setName] = useState("");
  useEffect(() => {
    AOS.init();
  });
  const handleChange = (e) => {
    if (e.target.name == "organisation") {
      setName(e.target.value);
    }
  };

  return (
    <div className="text-white text-center">
      <Head>
        <title>Strong Roots projects</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="my-6 ">
        <div className="pb-4" >
          <picture>
            <img src="/plant1.avif" alt="" className="w-32 rounded-full mx-auto" />
          </picture>
        </div>
        <input
          list="languages"
          className="bg-white text-black border-2 outline-2 text-lg outline-offset-2 outline-green-600 p-2 px-4 font-semibold rounded-lg"
          placeholder="serach by mandal"
          name="organisation"
          value={name}
          onChange={handleChange}
        />
        <p className="text-xs pt-2 text-gray-500" >enter the mandal name to find your institute</p>
      </div>
      <datalist id="languages" className="font-semibold">
        {village.map((item) => {
          return (
            <option
              className="bg-red-500 font-semibold"
              key={item}
              value={item}
            />
          );
        })}
      </datalist>
      <div className="">
        <div className="flex flex-row flex-wrap justify-around mx-4 ">
          {school &&
            school.map((item) => {
              return (
                <div
                  key={item.Village}
                  className="text-white "
                  data-aos="flip-left"
                  data-aos-duration="2000"
                >
                  {item.Mandal.includes(name) && (
                    <div className="p-4 mx-2 my-2 shadow-md shadow-green-500   ">
                      <div className="h-full bg-gray-800 bg-opacity-40 px-12 py-16 rounded-lg overflow-hidden text-center relative">
                        <h2 className="tracking-widest text-sm title-font font-medium text-gray-500 mb-1">
                          Name of the Institute
                        </h2>
                        <h1 className="title-font sm:text-2xl text-xl font-bold text-white mb-3  first-letter:uppercase ">
                          {item.Organization_Name}
                        </h1>

                        <table className="table-auto  w-fit mx-auto">
                          <tr>
                            <th className="text-center text-gray-500 font-medium text-sm">
                              Organization Type :{" "}
                            </th>
                            <th className="text-center text-green-400  px-4  font-semibold">
                              Government
                            </th>
                          </tr>

                          <tr>
                            <td className="text-end text-gray-500 font-medium text-sm">
                              Village :
                            </td>
                            <td className="text-center text-green-400  px-4  font-semibold">
                              {item.Village}
                            </td>
                          </tr>
                          <tr>
                            <td className="text-end text-gray-500 font-medium text-sm">
                              Mandal :{" "}
                            </td>
                            <td className="text-center text-green-400  px-4  font-semibold">
                              {item.Mandal}
                            </td>
                          </tr>
                          <tr>
                            <td className="text-end text-gray-500 font-medium text-sm">
                              District :{" "}
                            </td>

                            <td className="text-center text-green-400  px-4  font-semibold">
                              {item.District}
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
        </div>
      </div>
    </div>
  );
};
export async function getStaticProps({ params }) {
  return {
    props: { school: files, village: mandal }, // will be passed to the page component as props
  };
}

export default Plant;
